/*
* George Westfall
* CIS255
* File: HMwK14.java
* Project: Homework 14
*
* Write a Java class HmWk14. Create the method readTalkshow(list) in the HmWk14 class that 
* that reads the file TALKSHOW.DAT. Each line in the data file will be stored into a Host 
* Java class object and added to a list of Host objects. Make a note that the date in the 
* file needs to be converted to a Date object before setting the birthday field in the Host 
* class. Once the file has been read and saved into a list of Host objects, create another 
* method displayTalkshow(list) which iterates the list and display the information for each 
* talk show host. Create the class HmWk14 in the Java package 
* edu.calhoun.cis.java.intro.homework.homework14.
*
* Create the method writeTalkshow() to the HmWk14 class in Question #1 that that writes the 
* Host objects to a new data file TALKSHOW_NEW.DAT. The birthday must be written in the format 
* MM/DD/YYYY. Before writing the hosts to the new file, add a new Host object to the list by creating 
* the method addHost(List<Host> hosts, String lastName, String firstName, String hostNumber, 
* String birthday) and passing it the following values:
*       Last Name: Meyers
*       First Name: Seth
*       Host Number: 0008
*       Birthday: 12/28/1973
*
* Show the output generated by executing this program and show the contents of the newly created 
* TALKSHOW_NEW.DAT.
*
*/import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

import edu.calhoun.cis.java.intro.Host;

public class HmWk14 {
    public static void main(String[] args) {
        List<Host> hosts = new ArrayList<Host>();

        readTalkshow(hosts);

        displayTalkShowList(hosts);

        addHost(hosts, "Meyers", "Seth", "0008", "12/28/1973");

        writeTalkShow(hosts);
    }

    public static void writeTalkShow(List<Host> list)  {
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        FileOutputStream fOutput = null;
        BufferedWriter bWritter = null;

        try  {
            File file = new File(System.getProperty("java.class.path")
                + System.getProperty("file.separator") + "TALKSHOW_NEW.DAT");
            
            fOutput = new FileOutputStream(file);
            bWritter = new BufferedWriter(new OutputStreamWriter(fOutput));

            for (Host host: list)  {
                String birthday = formatter.format(host.getBirthday());

                bWritter.write(host.getFirstName() + " "
                        + host.getLastName() + " "
                        + host.getHostNumber() + " "
                        + birthday
                        + System.getProperty("line.separator"));
                bWritter.flush();
            }
        } catch(Exception exp)  {
            exp.printStackTrace();
        } finally  {
            try  {
                fOutput.close();
            } catch(Exception exp)  {
            }
            try  {
                bWritter.close();
            } catch(Exception e)  {
            }
        }

    }

    public static void addHost(List<Host> list, String lastName, String firstName, String hostNumber, String birthday ) {
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        Host host = null;
        Date date = null;

        try {
            date = formatter.parse(birthday);
        } catch(Exception e) {
            e.printStackTrace();
        }

        host = new Host(firstName, lastName, hostNumber, date);

        list.add(host);
    }

    public static void readTalkshow(List<Host> list)  {
        FileInputStream fInput = null;
        BufferedReader bReader = null;
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");

        try  {
            String line;

            formatter = new SimpleDateFormat("MM/dd/yyyy");

            File file = new File(System.getProperty("java.class.path")
                    + System.getProperty("file.separator") + "TALKSHOW.DAT" );

            fInput = new FileInputStream(file);
            bReader = new BufferedReader(new InputStreamReader(fInput));

            while ((line = bReader.readLine()) != null)  {
                StringTokenizer token = new StringTokenizer(line, " ");
                Host host = new Host();

                host.setFirstName(token.nextToken());
                host.setLastName(token.nextToken());
                host.setHostNumber(token.nextToken());

                Date birthday = formatter.parse(token.nextToken());
                host.setBirthday(birthday);

                list.add(host);
            }

        } catch(Exception exp)  {
            exp.printStackTrace();
        } finally  {
            try  {
                fInput.close();
            } catch(Exception exp)  {
            }
            try  {
                bReader.close();
            } catch(Exception e)  {
            }
        }
    }

    public static void displayTalkShowList(List<Host> list)  {
        for (Host host: list)  {
            System.out.println(host);
        }

    }


}
